task :default do
  leveldb_dir = File.expand_path('../leveldb', __FILE__)

  unless File.directory?(leveldb_dir)
    STDERR.puts "ext/leveldb missing, please checkout its submodule..."
    exit 1
  end

  # Make sure leveldb is built...
  system "cd #{leveldb_dir} && make" || exit(1)
end
